# Generated by Django 4.0.4 on 2022-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizgroup',
            name='quizes',
        ),
        migrations.AddField(
            model_name='quizgroup',
            name='quizes',
            field=models.ManyToManyField(to='main.quesmodel'),
        ),
    ]
